Repository nextcloud/files_retention, pull requests merged in 2022-10, with the labels that each got.

#209 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#208 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#216 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies

#212 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#213 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#214 Updating phpunit-oci.yml workflow from template
  .github/workflows/phpunit-oci.yml
Labels: dependencies

#215 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#217 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#219 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#218 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#220 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#221 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#229 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#228 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#227 Lang style/consistency - "Delete retention rule … deleted" -> "Retent…
  src/Components/RetentionRule.vue
Labels: bug, 4. to release, backport-request

#235 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#234 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#233 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
