Repository nextcloud/files_retention, pull requests merged in 2022-04, with the labels that each got.

#158 Update actions
  .github/dependabot.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  .gitignore
  .php-cs-fixer.dist.php
  Makefile
  composer.json
  composer.lock
Labels: 3. to review

#159 Make sure strings are translated
  js/retentionmodel.js
  js/retentionview.js
  templates/admin.php
Labels: bug, 3. to review

#160 Fix script loading for new js dist files for core/
  lib/Settings/Admin.php
  templates/admin.php
Labels: bug, 3. to review, backport-request

#162 Fix all the psalm issues and do php 7.4 cleanup
  composer.json
  lib/BackgroundJob/RetentionJob.php
  lib/Controller/APIController.php
  psalm.xml
  tests/lib/Contoller/APIControllerTest.php
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review

#165 Update appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml
Labels: backport-request
