Repository nextcloud/files_retention, pull requests merged in 2023-11, with the labels that each got.

#397 Fix compatibility with 28
  .github/workflows/phpunit-oci.yml
  composer.json
  lib/AppInfo/Application.php
  lib/BackgroundJob/RetentionJob.php
  lib/Constants.php
  lib/Controller/APIController.php
  lib/EventListener.php
  lib/Migration/Version010700Date20191125104957.php
  lib/Migration/Version011000Date20210206170027.php
  lib/Notification/Notifier.php
  lib/Settings/Admin.php
  psalm.xml
  tests/lib/EventListenerTest.php
Labels: bug, 3. to review

#358 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#351 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#359 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#402 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#405 fix(deps): Fix OCP package version
  composer.json
  composer.lock
Labels: bug, 3. to review

#399 Bump nextcloud vue libraries
  package-lock.json
  package.json
  screenshots/1.png
  src/AdminSettings.vue
  src/main.js
Labels: enhancement, 3. to review

#414 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#418 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#412 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#422 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#423 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
