Repository nextcloud/files_retention, pull requests merged in 2024-05, with the labels that each got.

#530 Add SPDX headers
  .github/workflows/reuse.yml
  .reuse/dep5
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-only.txt
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  Makefile
  appinfo/info.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/RetentionJob.php
  lib/Constants.php
  lib/Controller/APIController.php
  lib/EventListener.php
  lib/Migration/Version010700Date20191125104957.php
  lib/Migration/Version011000Date20210206170027.php
  lib/Notification/Notifier.php
  lib/Settings/Admin.php
  screenshots/1.png.license
  templates/admin.php
Labels: 3. to review, technical debt

#531 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
  README.md
Labels: dependencies

#537 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#540 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#543 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#542 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#541 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#546 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#548 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#549 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
