Repository nextcloud/files_retention, pull requests merged in 2024-02, with the labels that each got.

#468 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#469 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#461 fix(retention): Recreate retention job when loading admin settings
  lib/Controller/APIController.php
  tests/lib/BackgroundJob/RetentionJobTest.php
  tests/lib/Contoller/APIControllerTest.php
Labels: bug, 3. to review

#471 [stable28] chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#473 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#470 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#478 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#484 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#479 fix(UI): Fix default settings for "Unit" and "From date of"
  src/AdminSettings.vue
Labels: bug, 3. to review
