Repository nextcloud/files_retention, pull requests merged in 2024-07, with the labels that each got.

#573 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#576 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#577 Migrate REUSE to TOML format
  .reuse/dep5
  README.md
  REUSE.toml
  img/app-dark.svg
  img/app.svg
Labels: 4. to release

#579 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#580 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#581 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#578 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#582 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#583 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#585 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#586 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#588 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#587 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
