Repository nextcloud/files_retention, pull requests merged in 2024-04, with the labels that each got.

#513 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#512 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#514 fix(settings): Fix not working filter/search option in admin settings
  package-lock.json
  package.json
  src/AdminSettings.vue
Labels: backport-request

#519 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#520 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#522 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#529 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#525 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#524 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#523 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies
