Repository nextcloud/files_retention, pull requests merged in 2024-01, with the labels that each got.

#443 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#445 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#444 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#448 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#449 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#440 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#453 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#454 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#455 Version 1.17.0 - 2024-01-22
  CHANGELOG.md
Labels: 3. to review

#460 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
