Repository nextcloud/files_retention, pull requests merged in 2025-08, with the labels that each got.

#827 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#828 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#835 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#836 build: update node and npm engines versions
  package.json
Labels: dependencies

#837 Migrate to outlined icon
  src/Components/RetentionRule.vue
Labels: design, 3. to review

#839 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
