Repository nextcloud/files_retention, pull requests merged in 2025-04, with the labels that each got.

#756 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#758 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#757 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#755 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#763 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#762 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#761 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#764 fix(retention): Consider upload when using modification time
  lib/BackgroundJob/RetentionJob.php
  screenshots/1.png
  tests/lib/BackgroundJob/RetentionJobTest.php
Labels: bug, 3. to review, backport-request

#745 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#710 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#771 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#770 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#774 chore(release): Add changelog for 1.19.1 and 2.0.1
  CHANGELOG.md
Labels: backport-request

#780 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#781 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#779 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
