Repository nextcloud/files_retention, pull requests merged in 2025-01, with the labels that each got.

#697 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#696 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#698 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#699 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#700 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#692 fix(notifications): Notifier::prepare() threw \InvalidArgumentExcepti…
  lib/Notification/Notifier.php
Labels: 3. to review

#702 fix(settings): Show placeholder for tag selection
  src/AdminSettings.vue
Labels: bug, 3. to review

#706 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#707 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#708 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#709 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#711 chore(CI): Updating npm-audit-fix.yml workflow from template
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies
